name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-mingw:
    runs-on: windows-latest
    name: Test mingw-${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        include: [
          { msystem: MINGW64, arch: x86_64, rust_target: x86_64-pc-windows-gnu },
          # { msystem: MINGW32, arch: i686, rust_target: i686-pc-windows-gnu }
        ]
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4

      - name: Install msys2 and dependencies
        uses: msys2/setup-msys2@v2
        with:
          update: true
          path-type: inherit
          msystem: ${{ matrix.msystem }}
          install: >-
            mingw-w64-${{ matrix.arch }}-toolchain
            mingw-w64-${{ matrix.arch }}-python
            mingw-w64-${{ matrix.arch }}-cython
            mingw-w64-${{ matrix.arch }}-python-pip
            mingw-w64-${{ matrix.arch }}-python-poetry
            mingw-w64-${{ matrix.arch }}-python-maturin

      - name: Install Rustup using win.rustup.rs
        run: |
          curl -o rustup-init.exe -sSL https://win.rustup.rs/
          ./rustup-init.exe -y --default-host=${{ matrix.rust_target }} --profile=minimal
          rm rustup-init.exe

      - name: Install Rust
        run: |
          rustup install stable --profile minimal
          rustup default stable
          rustup target add ${{ matrix.rust_target }}

      - name: Install Poetry
        run: |
          export SETUPTOOLS_USE_DISTUTILS=stdlib
          poetry install

      - name: Create libpython symlink
        run: ln -s /${{ matrix.path }}/lib/libpython3.11.dll.a /${{ matrix.path }}/lib/libpython311.dll.a

      - name: Install
        run: poetry run maturin develop --release

      - name: Test
        run: poetry run pytest ./tests

      - name: Build
        run: poetry run maturin build --release --out dist --no-default-features --target ${{ matrix.rust_target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: hello-world ${{ runner.os }} - ${{ matrix.rust_target }}
          path: dist